### ISSUE TITLE
The user does not have the rights

### ISSUE THREAD

**Issue by ITRecords38** [vdesabou/alfred-convert-word-to-pdf#3]
Hi,

I have given full access to my disk and some documents do not convert (see the screenshot)

My documents are on my Onedrive

Thanks
<img width="416" alt="convert" src="https://user-images.githubusercontent.com/19632490/118234310-74efd900-b493-11eb-8be8-484a67d0e49c.png">

**Comment by vdesabou** [comment]
This workflow was only working with Word 2011. I will archive this repo as I don't even have word anymore.
Sorry I cannot help here
